### PR TITLE
French review of aliases

### PR DESCRIPTION
**Pull request by Zgzorx**
A draft to see if everything is right

### CODE REVIEW

**Comment by Zgzorx** [comment]
Seems pretty good now

**Comment by LittleFool** [comment]
can you add a line in the remove script for TheLounge, irssi and weechat for frsafe-fr ?

**Comment by Zgzorx** [comment]
Seems like removing frsafe wasn't handled in irssi

**Comment by Zgzorx** [comment]
> can you add a line in the remove script for TheLounge, irssi and weechat for frsafe-fr ?

Should be done

**Pull request merged**
